SELECT F.FLAVOR
FROM FIRST_HALF AS F
INNER JOIN ICECREAM_INFO AS I
ON F.FLAVOR = I.FLAVOR -- 조인 기준(조건)
WHERE F.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE LIKE 'fruit_based' -- 전체 조건
ORDER BY F.TOTAL_ORDER DESC