SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I
INNER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SEX_UPON_INTAKE != SEX_UPON_OUTCOME; -- SOL1
-- WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND O.SEX_UPON_OUTCOME NOT LIKE 'Intact%'; (SOL2)
-- WHERE SEX_UPON_INTAKE <> SEX_UPON_OUTCOME; -- <>는 !=와 같음 (다르다) (SOL3)