-- SOL 1) JOIN 없이 WHERE, NOT IN 으로
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I
-- 교집합을 가져오는 것이 아니므로 JOIN 할 필요 X
WHERE I.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY I.DATETIME ASC
LIMIT 3;


-- SOL 2) LEFT JOIN
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O -- 왼쪽으로 합치고 오른쪽에서는 공통인 애만 가져옴
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL -- 오른쪽 중 공통이 아닌 애는 NULL로 가져옴
ORDER BY I.DATETIME ASC
LIMIT 3;

-- SOL 3) RIGHT JOIN
SELECT I.NAME, I.DATETIME -- O 아니고 I에서 SELECT 해야 값 나옴!
FROM ANIMAL_OUTS AS O
RIGHT JOIN ANIMAL_INS AS I -- RIGHT JOIN 시, 오른쪽 테이블이 SELECT 결과로 나옴
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME ASC
LIMIT 3;